version: '3.7'
services:
    database:
        image: mysql:latest
        container_name: scombnb_mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: scombnb_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
